/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_blackberry_bdp_kaboom_FastBoomWriter */

#ifndef _Included_com_blackberry_bdp_kaboom_FastBoomWriter
#define _Included_com_blackberry_bdp_kaboom_FastBoomWriter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_blackberry_bdp_kaboom_FastBoomWriter
 * Method:    compress
 * Signature: ([BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_blackberry_bdp_kaboom_FastBoomWriter_compress
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
